url: https://ines-tonato.github.io/
baseurl: 
permalink: pretty
title: 'Jekyll Serif'

logo:
  mobile: "images/E-aprende.png"
  mobile_height: "32px"
  mobile_width: "32px"
  desktop: "images/E-aprende.png"
  desktop_height: "32px"
  desktop_width: "120px"

home: 
  limit_collections: 6

collections:
  collections:
    output: true
    sort_by: weight
  post:
    output: true

defaults:
  - scope:
      path: ""
      type: "collections"
    values:
      layout: "collection"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  style: compressed # possible values: nested expanded compact compressed

plugins:
  - jekyll-environment-variables

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - LICENSE.md
  - LICENSE
  - README.md
